// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "@rescript/std/lib/es6/caml_option.js";

function flatten(v) {
  if (v === undefined) {
    return ;
  }
  var x = Caml_option.valFromOption(v);
  if (x !== undefined) {
    return Caml_option.some(Caml_option.valFromOption(x));
  }
  
}

export {
  flatten ,
  
}
/* No side effect */
