// Generated by ReScript, PLEASE EDIT WITH CARE


function multiplySelf(param) {
  return Math.imul(param[0], param[1]);
}

function sumSelf(param) {
  return param[0] + param[1] | 0;
}

var Tuple2 = {
  multiplySelf: multiplySelf,
  sumSelf: sumSelf
};

function multiplySelf$1(param) {
  return Math.imul(Math.imul(param[0], param[1]), param[2]);
}

function sumSelf$1(param) {
  return (param[0] + param[1] | 0) + param[2] | 0;
}

var Tuple3 = {
  multiplySelf: multiplySelf$1,
  sumSelf: sumSelf$1
};

export {
  Tuple2 ,
  Tuple3 ,
  
}
/* No side effect */
