// Generated by ReScript, PLEASE EDIT WITH CARE


function xor(a, b) {
  if (a || b) {
    return !(a && b);
  } else {
    return false;
  }
}

function xnor(a, b) {
  return !xor(a, b);
}

export {
  xor ,
  xnor ,
  
}
/* No side effect */
