// Generated by ReScript, PLEASE EDIT WITH CARE


function expectInt(name, expected, actual) {
  console.log(actual === expected ? name + " -- Pass ✅" : name + " -- Fail ❌ expected " + String(expected) + " but got " + String(actual));
  
}

export {
  expectInt ,
  
}
/* No side effect */
